apiVersion: v1
kind: Service
metadata:
  name: appflowy
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: appflowy
  ports:
  - port: {{ .Values.ports.nginx }}
    targetPort: {{ .Values.ports.nginx }}
    protocol: TCP
    name: http