apiVersion: v1
kind: Service
metadata:
  name: appflowy-cloud
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: appflowy-cloud
  ports:
  - port: {{ .Values.ports.cloud }}
    targetPort: {{ .Values.ports.cloud }}
    protocol: TCP
    name: http