apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - port: {{ .Values.ports.minioApi }}
    targetPort: {{ .Values.ports.minioApi }}
    protocol: TCP
    name: api
  - port: {{ .Values.ports.minioConsole }}
    targetPort: {{ .Values.ports.minioConsole }}
    protocol: TCP
    name: console