apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: admin-frontend
  ports:
  - port: {{ .Values.ports.admin }}
    targetPort: {{ .Values.ports.admin }}
    protocol: TCP
    name: http