apiVersion: v1
kind: Service
metadata:
  name: gotrue
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: gotrue
  ports:
  - port: {{ .Values.ports.gotrue }}
    targetPort: {{ .Values.ports.gotrue }}
    protocol: TCP
    name: http