apiVersion: v1
kind: Service
metadata:
  name: appflowy-web
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: appflowy-web
  ports:
  - port: {{ .Values.ports.web }}
    targetPort: {{ .Values.ports.web }}
    protocol: TCP
    name: http