apiVersion: v1
kind: Service
metadata:
  name: appflowy-ai
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: appflowy-ai
  ports:
  - port: {{ .Values.ports.ai }}
    targetPort: {{ .Values.ports.ai }}
    protocol: TCP
    name: http