apiVersion: v1
kind: Service
metadata:
  name: appflowy-search
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: appflowy-search
  ports:
  - port: {{ .Values.ports.search }}
    targetPort: {{ .Values.ports.search }}
    protocol: TCP
    name: http