apiVersion: v2
name: appflowy
description: AppFlowy Cloud self-hosted server for Olares — sync hub for AppFlowy desktop/mobile/web clients.
type: application
version: 1.2.2
appVersion: "0.18.9"
home: https://appflowy.io
sources:
  - https://github.com/AppFlowy-IO/AppFlowy
  - https://github.com/AppFlowy-IO/AppFlowy-Cloud
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/appflowy.png
maintainers:
  - name: abidals
keywords:
  - notes
  - knowledge
  - workspace
  - notion-alternative